on:
  workflow_call:
    inputs:
      context:
        type: string
        description: Build context
        required: false
        default: "."
      images:
        type: string
        description: List of image names
        required: true
      tags:
        type: string
        description: |
          Tagging strategy used by docker/metadata-actions@v3 action. By default, uses
          semver > pr > branch in this order.
        required: false
        default: |
          type=semver,pattern={{version}}
          type=ref,event=pr
          type=ref,event=branch
      platforms:
        type: string
        description: List of target platforms to build images for
        required: false
        default: linux/amd64
      push:
        type: boolean
        description: Whether to push the image to remote repository
        required: false
        default: false
      registry:
        type: string
        description: Address of the docker registry when pushing image
        required: false
        default: ghcr.io
    secrets:
      registry_username:
        required: false
      registry_password:
        required: false

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Tagging
        id: tagging
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.images }}
          tags: ${{ inputs.tags }}
      - name: Login into registry
        uses: docker/login-action@v1
        if: ${{ inputs.push }}
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ inputs.push }}
          tags: ${{ steps.tagging.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload image tar
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar
